- README.md
- cmd/rootlesskit/main.go
- pkg/child/child.go
- pkg/child/resolvconf.go
- pkg/parent/parent.go
- pkg/parent/slirp.go
>  github.com/AkihiroSuda/rootlesskit -> github.com/rootless-containers/rootlesskit

- .travis.yml
- README.md
- cmd/rootlesskit/main.go
- hack/test.sh
- hack/test/Dockerfile
- hack/test/docker-entrypoint.sh
> add containerized benchmark suite

- README.md
- cmd/rootlesskit/main.go
- hack/test.sh
- hack/test/Dockerfile
- hack/test/docker-entrypoint.sh
- pkg/child/child.go
- pkg/common/message.go
- pkg/parent/parent.go
- pkg/parent/slirp.go
slirp4netns can reach 8.18 Gbits/sec with MTU=65520: https://github.com/rootless-containers/slirp4netns/pull/20
> support --mtu

- hack/test/docker-entrypoint.sh
> benchmark: add MTU=4000

- pkg/parent/parent.go
> fix state dir clean-up

- Gopkg.lock
- Gopkg.toml
- pkg/parent/parent.go
- vendor/github.com/opencontainers/runc/libcontainer/user/lookup_unix.go
> Fix subgid interpretation

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/moby/datakit/api/go-datakit/client.go
- vendor/github.com/opencontainers/runc/libcontainer/user/lookup_unix.go
Enables building rootlesskit on 32bit architectures https://github.com/moby/datakit/pull/638
Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>
> vendor: update datakit

- hack/test/Dockerfile
> unfork newuidmap/newgidmap

- pkg/parent/parent.go
#30 
I fix unix domain socket is unlinked before net.Listen
> unlink before bind #30

- hack/test/Dockerfile
> test: use prebuilt vpnkit binary

- pkg/port/socat/socat.go
- pkg/port/testsuite/testsuite.go
> port/socat: support UDP

- pkg/network/iputils/iputils.go
- pkg/version/version.go
> v0.3.0-alpha.1 (support 32bit archs)

- cmd/rootlesskit/main.go
> remove unneeded warning

- hack/test/Dockerfile
> test: update slirp4netns, vpnkit

- README.md
- cmd/rootlessctl/main.go
- cmd/rootlesskit/main.go
- pkg/parent/parent.go
> set $ROOTLESSKIT_STATE_DIR for the child process

- Makefile
- cmd/rootlesskit-docker-proxy/main.go
- pkg/version/version.go
Usage: `dockerd-rootless.sh --experimental --userland-proxy --userland-proxy-path=/path/to/rootlesskit-docker-proxy`
>  add rootlesskit-docker-proxy (v0.3.0-beta.0)

- pkg/parent/parent.go
Follow-up to #53  cc @jaredbancroft
> parent: clean up

- pkg/port/builtin/builtin.go
> port/builtin: remove fifo before creating

- pkg/child/child.go
- pkg/common/message.go
- pkg/parent/parent.go
> reexec child to obtain caps

- README.md
- cmd/rootlesskit/main.go
> deprecate support for vdeplug_slirp

- README.md
- cmd/rootlesskit/main.go
- pkg/child/child.go
- pkg/parent/parent.go
- pkg/version/version.go
Fix #65
@ibuildthecloud @giuseppe
> support unsharing PIDNS (--pidns) (release v0.5.0)

- hack/test/Dockerfile
https://github.com/moby/vpnkit/compare/67041ad2655038c5462b3466f89a1853f2b894e5...7dd3dcce7d3d8ffa85d43640f70158583d6fa882
> test: update vpnkit binary

- cmd/rootlesskit/main.go
- pkg/network/slirp4netns/slirp4netns.go
Requires slirp4netns v0.4.0-beta.2 (https://github.com/rootless-containers/slirp4netns/pull/105)
The default value is `false` currently, but planned to be `auto` in the
future.
> slirp4netns: support --slirp4netns-sandbox=auto/true/false

- pkg/network/slirp4netns/slirp4netns.go
> slirp4netns: wait for ready FD to be written

- pkg/child/child.go
Fixes #90 
Switch from mount(8) to mount(2) syscall
Signed-off-by: Boris Popovschi <zyqsempai@mail.ru>
> Switch from mount(8) to mount(2) syscall

- pkg/parent/parent.go
Fixes #37 
Signed-off-by: Boris Popovschi <zyqsempai@mail.ru>
> Moved writing to child_pid file after child configuration

- cmd/rootlesskit/main.go
- pkg/network/slirp4netns/slirp4netns.go
Fix #142 
NOTE: stdout is not captured
> redirect slirp4netns stderr to logrus.Debug

- pkg/parent/idtools/idtools.go
- pkg/parent/parent.go
> idtools: support numeric IDs + misc fixes

- pkg/port/builtin/child/child.go
> port/builtin: fix FD leak

- README.md
- cmd/rootlesskit/main.go
- pkg/network/lxcusernic/lxcusernic.go
- pkg/network/vpnkit/vpnkit.go
> support specifying --ifname for VPNKit and lxc-user-nic

- .github/workflows/main.yaml
- cmd/rootlesskit/main.go
- hack/integration-restart.sh
- pkg/parent/parent.go
> fix cleaning up crashed state dir

- README.md
Signed-off-by: haozi007 <knowledgehao@163.com>
> add container engine iSulad which use rootlesskit

- go.mod
- go.sum
Signed-off-by: Wenlong Zhang <zhangwenlong@loongson.cn>
> update sys and net for go.mod

- .github/workflows/release.yaml
- pkg/version/version.go
> CI: attest-build-provenance: fix a subject-path issue 
