- README.md
- cmd/rootlesskit/main.go
- pkg/child/child.go
- pkg/common/common.go
- pkg/common/message.go
- pkg/parent/parent.go
- pkg/parent/slirp.go
Host:
```console
$ iperf3 -c 127.0.0.1 -t 30
...
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-30.00  sec   153 GBytes  44.0 Gbits/sec    2             sender
[  4]   0.00-30.00  sec   153 GBytes  44.0 Gbits/sec                  receiver
```
VPNKit:
```console
$ rootlesskit --net=vpnkit iperf3 -c 192.168.65.2 -t 30
...
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-30.00  sec  1.44 GBytes   413 Mbits/sec    0             sender
[  4]   0.00-30.00  sec  1.44 GBytes   412 Mbits/sec                  receiver
```
vdeplug_slirp:
```console
$ rootlesskit --net=vdeplug_slirp iperf3 -c 10.0.2.2 -t 30
...
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-30.00  sec   787 MBytes   220 Mbits/sec    0             sender
[  4] …
```
> fix vpnkit buffer size + support slirp4netns

- pkg/child/child.go
- pkg/child/hosts.go
Without this fix, Usernetes does not work because the hostname
is resolved into the IP address of the eth0 in the host network namespace.
$ ./kubectl.sh run -it --rm --image alpine foo
If you don't see a command prompt, try pressing enter.
Error attaching, falling back to logs: error dialing backend: dial tcp 10.138.0.2:10250: connect: connection refused
deployment.apps "foo" deleted
Error from server: Get https://oregon:10250/containerLogs/default/foo-68d78ff5c9-t97fr/foo: dial tcp 10.138.0.2:10250: connect: connection refused
> add `127.0.0.1 $HOSTNAME` to /etc/hosts

- hack/test/Dockerfile
- hack/test/docker-entrypoint.sh
> test: add rootful_veth benchmark for comparison

- hack/test.sh
- hack/test/Dockerfile
- pkg/child/child.go
EDIT: waiting for https://github.com/docker/cli/pull/1347 to be merged
- - -
With https://github.com/shadow-maint/shadow/pull/132 , we should no longer need `--privileged` for running RootlessKit inside Docker containers.
> update Dockerfile, with Giuseppe's newuidmap

- README.md
- cmd/rootlesskit/main.go
- hack/test/Dockerfile
- pkg/network/iputils/iputils.go
- pkg/network/iputils/iputils_test.go
- pkg/network/slirp4netns/slirp4netns.go
Requires slirp4netns v0.3.0-alpha.0 or later
> support specifying slirp4netns CIDR

- pkg/copyup/tmpfssymlink/tmpfssymlink.go
- pkg/version/version.go
>  copyup/tmpfssymlink: delete target path before creating symlink (v0.3.0-alpha.2)

- pkg/child/child.go
- pkg/version/version.go
The parent calls child with Pdeathsig, but it is cleared when newuidmap SUID binary is called
https://github.com/rootless-containers/rootlesskit/issues/65#issuecomment-492343646
> child: reconfigure Pdeathsig (release v0.4.1)

- README.md
- cmd/rootlesskit/main.go
- pkg/parent/parent.go
- pkg/version/version.go
> rootlesskit: add -p for publishing ports (similar to `docker run -p`) (v0.6.0)

- cmd/rootlesskit/main.go
- pkg/network/slirp4netns/slirp4netns.go
the flag was introduced in slirp4netns v0.4.0-beta.2 and then renamed in beta.4
https://github.com/rootless-containers/slirp4netns/pull/137
> slirp4netns: --create-sandbox -> --enable-sandbox

- README.md
- cmd/rootlesskit/main.go
NOTE: This commit deprecates `slirp4netns` *port* driver (ingress), but does NOT deprecate `slirp4netns` *network* driver (egress).
> port: move `builtin` out of experimental; deprecate `socat` and `slirp4netns`

- hack/test/docker-entrypoint.sh
- pkg/port/builtin/builtin.go
- pkg/port/builtin/udpproxy/udp_proxy.go
> port/builtin: use libnetwork UDP proxy

- pkg/child/child.go
Fix regression https://github.com/rootless-containers/usernetes/pull/119#issuecomment-569978202
> child: avoid empty string as a mount source

- pkg/child/hosts.go
- pkg/child/resolvconf.go
- pkg/copyup/tmpfssymlink/tmpfssymlink.go
Fix #90 
Signed-off-by: Boris Popovschi <zyqsempai@mail.ru>
> Switch from mount(8) to mount(2) syscall, final

- cmd/rootlesskit/main.go
- pkg/child/child.go
A new field Reaper is added to child.Opts to run a process
reaper when running the child target command.  This is needed
if you are running the child in a new PID namespace and you wish
to avoid zombies.
> Add reaper functionality to child

- README.md
- cmd/rootlesskit/main.go
- pkg/parent/parent.go
The parent EUID is propagated into the child via $ROOTLESSKIT_PARENT_EUID .
> new env var: $ROOTLESSKIT_PARENT_EUID

- pkg/version/version.go
Notable changes since v0.8.0:
* Support `--propagation=(rprivate|rslave)`. The default value remains `rprivate`, but `rslave` is more useful in most cases. `rshared` doesn't work with `--copy-up` and isn't useful. (#109)
* Removed support for `--net=vdeplug_slirp`. `vdeplug_slirp` has been already deprecated since v0.4.0. (#113)
> v0.9.0-beta.0

- cmd/rootlesskit/main.go
- pkg/parent/mount/mount.go
- pkg/parent/mount/mount_linux.go
- pkg/parent/mount/mountinfo.go
- pkg/parent/parent.go
- pkg/parent/warn.go
- pkg/version/version.go
* print warning when unsupported propagation was specified (Suggested in https://github.com/moby/moby/pull/40635#issuecomment-595829139 , CC @thaJeztah @cpuguy83)
* print sysctl warnings
* print warning if running as root
> print warning when preconditions are not satisfied + release v0.9.1

- pkg/child/child.go
- pkg/parent/parent.go
- pkg/sigproxy/signal/signal.go
- pkg/sigproxy/signal/signal_linux.go
- pkg/sigproxy/signal/signal_linux_mipsx.go
- pkg/sigproxy/sigproxy.go
Before:
```console
$ dockerd-rootless.sh --experimental
...
INFO[2020-03-15T11:02:16.526051714+09:00] API listen on /run/user/1001/docker.sock     
^C
$ echo $?
130
```
After:
```console
$ dockerd-rootless.sh --experimental
...
INFO[2020-03-15T11:02:42.263959577+09:00] API listen on /run/user/1001/docker.sock     
^CINFO[2020-03-15T11:02:43.493624366+09:00] Processing signal 'interrupt'                
INFO[2020-03-15T11:02:43.494655209+09:00] Processing signal 'interrupt'                
INFO[2020-03-15T11:02:43.495386457+09:00] stopping event stream following graceful shutdown  error="<nil>" module=libcontainerd namespace=moby
INFO[2020-03-15T11:02:43.495546067+09:00] Daemon shutdown complete                     
INFO[2020-03-15T11:02:43.495566660+09:00] stopping event stream following …
```
> support forwarding signals

- README.md
- cmd/rootlesskit-docker-proxy/main.go
- pkg/api/api.go
- pkg/api/client/client.go
- pkg/api/router/router.go
- pkg/port/builtin/parent/parent.go
Fix #135
---
Before:
```console
$ docker --context=rootless run -it -p 80:80 --rm alpine
docker: Error response from daemon: driver failed programming external connectiv
ity on endpoint clever_euclid (77c992ce4056362ee89727f4d2d96c349bbb9013b14f4f201
2412f2fbc94718e): Error starting userland proxy:.
```
After:
```console
$ docker --context=rootless run -it -p 80:80 --rm alpine
docker: Error response from daemon: driver failed programming external connectiv
ity on endpoint brave_murdock (71e0f00b4a8555cefd15d984d15f4dc255e4caa2ca5cc72df
8a04e463afc13b2): Error starting userland proxy: error while calling PortManager
.AddPort(): cannot expose privileged port 80, you might need to add "net.ipv4.ip
_unprivileged_port_start=0" (currently 1024) to /etc/sysctl.conf, or set CAP_NET
_BIND_SERVICE …
```
> rootlesskit-docker-proxy: report detailed error via FD 3

- README.md
- cmd/rootlesskit/main.go
- pkg/network/slirp4netns/slirp4netns.go
Support for slirp4netns v0.3.X has been broken since RootlessKit v0.7.1.
Also, slirp4netns v0.3.X has reached EOL on Mar 31, 2020.
Fix https://github.com/rootless-containers/rootlesskit/issues/143
> Officially drop support for slirp4netns v0.3.X

- cmd/rootlesskit/main.go
- pkg/parent/parent.go
The new flag --cgroupns unshares the cgroup namespace for the child.
> cli: new flag: --cgroupns

- README.md
- cmd/rootlesskit/main.go
slirp4netns port driver is still useful, as it can preserve the src IP unlike the builtin driver.
> de-deprecate slirp4netns port driver

- cmd/rootlesskit/main.go
- pkg/parent/parent.go
- pkg/parent/parent_test.go
Hi all,
here is the FIX for the created issue #185 
If the user don't pass the `--state-dir` argument the internal `StateDirTemp` flag will be set.
On running the `Parent` function a Shared BSD Lock  [LOCK_SH](https://man7.org/linux/man-pages/man2/flock.2.html) will be set on the stateDir.
All locks will be removed with the `Rootlesskit` `StateFileLock` (`/tmp/rootlesskitXXX/lock`).
I also added a test to check if the lock was created, but to test that on a real system you have to read the verify part.
OS:  Ubuntu 18.04 LTS
1. Check tmp settings
`cat /usr/lib/tmpfiles.d/tmp.conf`
2. Change them if no cleanup for "old files" was configured.
`sudo nano /usr/lib/tmpfiles.d/tmp.conf`
See possible configuration settings: [tmpfiles.d(5)](https://man7.org/linux/man-pages/man5/tmpfiles.d.5.html) …
> Lock StateDir

- pkg/port/builtin/parent/parent.go
This error is showing up looking like
podman run -p 80:80 fedora echo hello
Error: failed to expose ports via rootlessport: "cannot expose privileged port 80, you might need to add \"net.ipv4.ip_unprivileged_port_start=0\" (currently 1024) to /etc/sysctl.conf, or choose a larger port number (>= 1024): listen tcp 0.0.0.0:80: bind: permission denied\n"
When run in Podman, trying to clean it up a little so the special chars \" to
not show up, and I think it makes more senset to tell users to start have priv
port, at least from a security point of view.  Users probably want to keep this above port 22.
net.ipv4.ip_unprivileged_port_start=80
Rather then
net.ipv4.ip_unprivileged_port_start=0
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>
> Fix up privileged port exposure

- go.sum
- pkg/port/builtin/child/child.go
- pkg/port/builtin/msg/msg.go
- pkg/port/port.go
- pkg/port/slirp4netns/slirp4netns.go
- pkg/port/socat/socat.go
allow users to override the IP to use for the connection inside the
network namespace.
It is useful e.g. with slirp4netns to override the IP to "10.0.2.100".
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
> port: add ChildIP

- .github/workflows/main.yaml
- cmd/rootlesskit/main.go
- hack/integration-exit-code.sh
- pkg/child/child.go
- pkg/common/exec.go
`rootlesskit --pidns` had been broken due to incomplete implementation of reaper:
```
$ rootlesskit --pidns /bin/true
[rootlesskit:child ] error: command [/bin/true] exited: waitid: no child processes
[rootlesskit:parent] error: child exited: exit status 1
```
Fix #129
> `rootlesskit --pidns`: fix propagating exit status

- Makefile
- README.md
- cmd/rootlesskit/main.go
- go.sum
- hack/integration-evacuate-cgroup2.sh
- pkg/child/child.go
- pkg/parent/cgrouputil/cgrouputil.go
- pkg/parent/parent.go
- pkg/version/version.go
e.g. `systemd-run -p Delegate=yes --user -t rootlesskit --cgroupns --pidns --evacuate-cgroup2=evac --net=slirp4netns bash`
When the current process belongs to `/foo` group (visible under `/sys/fs/cgroup/foo`) and evac is like `bar`,
- All processes in the `/foo` group are moved to `/foo/bar` group, by writing PIDs into `/sys/fs/cgroup/foo/bar/cgroup.procs`
- As many controllers as possible are enabled for `/foo/*` groups, by writing `/sys/fs/cgroup/foo/cgroup.subtree_control`
> support cgroup2 evacuation 

- pkg/port/builtin/parent/tcp/tcp.go
- pkg/port/builtin/parent/udp/udp.go
- pkg/port/portutil/portutil.go
- pkg/port/portutil/portutil_test.go
- pkg/port/socat/socat.go
Refactor of portutil, related to https://github.com/moby/moby/pull/41908 and https://github.com/rootless-containers/rootlesskit/pull/207
The PortSpec uses colons a delimiter between parts. If an IPv6 address is used, this leads to the colons in the IP-address to be handled as delimiter.
Commit 1d78bed8423d3377e04c4bdd1e1a045fb42e2942 (https://github.com/rootless-containers/rootlesskit/pull/207) also added support for "ChildIP" to the portspec format, which (adding to the above) made parsing the format even more ambiguous.
This patch rewrites ParsePortSpec to handle IPv6 addresses, but requires those addresses to be wrapped by square brackes.
There was an inconsistency between ParsePortSpec and ValidatePortSpec; ParsePortSpec accepted "sctp" as a valid proto, whereas ValidatePortSpec did …
> Refactor ParsePortSpec to handle IPv6 addresses, and improve validation

- pkg/port/socat/socat.go
As discussed in https://github.com/rootless-containers/rootlesskit/pull/213/files#r575905096
> pkg/port/socat: remove redundant sprintf

- README.md
- cmd/rootlesskit/category.go
- cmd/rootlesskit/main.go
```console
$ rootlesskit --help
NAME:
rootlesskit - Linux-native fakeroot using user namespaces
USAGE:
rootlesskit [global options] [arguments...]
VERSION:
0.13.2+dev
DESCRIPTION:
RootlessKit is a Linux-native implementation of "fake root" using user_namespaces(7).
Web site: https://github.com/rootless-containers/rootlesskit
Examples:
rootlesskit bash
rootlesskit --copy-up=/etc bash
rootlesskit --propagation=rslave bash
rootlesskit --copy-up=/etc --net=slirp4netns --disable-host-loopback --port-driver=builtin -p 127.0.0.1:8080:80/tcp bash
Note: RootlessKit requires /etc/subuid and /etc/subgid to be configured by the real root user.
OPTIONS:
Debug:                         
--debug                      debug mode (default: false)
Mount:                         
--copy-up value …
```
> CLI: improve `--help` output

- pkg/parent/cgrouputil/cgrouputil.go
- pkg/parent/cgrouputil/moby_sys_mountinfo_tmphack.go
Downstream projects (especially k3s) still depends on moby/sys/mountinfo@v0.1.3, which is incompatible with mountinfo@v0.4.0. ("Fstype" vs "FSType") https://github.com/moby/sys/commit/ad7461a5435ef0a9d6b8b89de26ec8c2da5f94a5
This commit adds `relect` hack to support vendoring with the both versions
> allow vendoring with moby/sys/mountinfo@v0.1.3 as well as @v0.4.0

- .github/workflows/main.yaml
- README.md
- cmd/rootlessctl/info.go
- cmd/rootlessctl/main.go
- cmd/rootlesskit-docker-proxy/main.go
- docs/api.md
- docs/port.md
- hack/integration-port.sh
- pkg/api/api.go
- pkg/api/client/client.go
- pkg/api/openapi.yaml
- pkg/api/router/router.go
- pkg/network/lxcusernic/lxcusernic.go
- pkg/network/network.go
- pkg/network/slirp4netns/slirp4netns.go
- pkg/network/vpnkit/vpnkit.go
- pkg/parent/parent.go
- pkg/port/builtin/child/child.go
- pkg/port/builtin/msg/msg.go
- pkg/port/builtin/parent/parent.go
- pkg/port/builtin/parent/tcp/tcp.go
- pkg/port/builtin/parent/udp/udp.go
- pkg/port/port.go
- pkg/port/portutil/portutil.go
- pkg/port/portutil/portutil_test.go
- pkg/port/slirp4netns/slirp4netns.go
- pkg/port/socat/socat.go
- pkg/port/testsuite/testsuite.go
e.g.
```console
$ rootlessctl info -json
{
"apiVersion": "1.1.0",
"version": "0.13.2+dev",
"stateDir": "/tmp/rootlesskit751356081",
"childPID": 163654,
"networkDriver": {
"driver": "slirp4netns",
"dns": [
"10.0.2.3"
]
},
"portDriver": {
"driver": "builtin",
"protos": [
"tcp",
"udp"
]
}
}
```
Inspecting `.portDriver.protos` is required for implementing https://github.com/rootless-containers/rootlesskit/issues/231#issuecomment-787714453
Fix #231
See `./docs.port.md`
```md
Specifying `0.0.0.0:8080:80/tcp` may cause listening on IPv6 as well as on IPv4.
Same applies to `[::]:8080:80/tcp`.
This behavior may sound weird but corresponds to [Go's behavior](https://github.com/golang/go/commit/071908f3d809245eda
42bf6eab071c323c67b7d2),
so this is not a bug.
To specify IPv4 explicitly, use `tcp4` …
```
> Port API: support specifying IP version explicitly ("tcp4", "tcp6")

- .github/workflows/main.yaml
- cmd/rootlesskit/main.go
- docs/network.md
- hack/integration-ipv6.sh
- pkg/network/slirp4netns/slirp4netns.go
Enables IPv6 routing (`slirp4netns --enable-ipv6`).
Unrelated to port driver.
> new experimental flag: --ipv6

- .github/workflows/main.yaml
- cmd/rootlessctl/info.go
- cmd/rootlessctl/port.go
- cmd/rootlesskit-docker-proxy/main.go
- pkg/api/api.go
- pkg/api/openapi.yaml
- pkg/network/lxcusernic/lxcusernic.go
- pkg/network/slirp4netns/slirp4netns.go
- pkg/network/vpnkit/vpnkit.go
- pkg/port/builtin/parent/parent.go
- pkg/port/slirp4netns/slirp4netns.go
- pkg/version/version.go
Fix rootless-containers/slirp4netns#261
> rootlesskit-docker-proxy: fix support for slirp4netns port driver

- README.md
Previously linked repository indicates that it has moved.
> nerdctl has moved

- .github/workflows/main.yaml
Docker builds RootlessKit with Go 1.13, so we should use Go 1.13 as well
for Docker integration tests.
> CI: test Go 1.13 compatibility

- pkg/port/builtin/parent/parent.go
- pkg/port/builtin/parent/tcp/tcp.go
- pkg/port/builtin/parent/udp/udp.go
RemovePort() should block until the connection is closed. This allows
the caller to safely use AddPort() afterwards.
Signed-off-by: Paul Holzinger <pholzing@redhat.com>
> port/builtin: RemovePort() block until conn is closed

- pkg/port/builtin/parent/parent.go
- pkg/port/builtin/parent/tcp/tcp.go
- pkg/port/builtin/parent/udp/udp.go
- pkg/version/version.go
Revert #262 (https://github.com/rootless-containers/rootlesskit/pull/262/files#r682338302) and add an alternative.
> port/builtin: RemovePort() block until conn is closed, take 2 + Release v0.14.4

- .github/workflows/main.yaml
- go.mod
* The Dockerfile already builds for go1.17. Therefore updating the go.mod to go1.17.
* Update README instructions to use go install instead of go get as go get won't add executable binaries in the future.
> Update go.mod to have go1.17 as the minmium version

- go.mod
- go.sum
Reverts rootless-containers/rootlesskit#305
Due to:
- https://github.com/urfave/cli/issues/1404
> Revert "Bump github.com/urfave/cli/v2 from 2.6.0 to 2.7.1"

- pkg/network/slirp4netns/slirp4netns.go
The error was incorreclty telling "this version of slirp4netns does not support --enable-sandbox" instead of "this version of slirp4netns does not support --enable-ipv6"
> Fix ipv6 feature error typo

- pkg/parent/dynidtools/dynidtools.go
In LDAP-based environments both `getsubids myusername` and `getsubids 1234` (where `id myusername` equals to `1234`) can return exactly the same subuid ranges. This happens when one of `/etc/subuid` or `nss` returns mappings for both the user id and the user name. Both `newgidmap` and `newuidmap` fail when the parameters contain duplicate ranges.
This PR fixes the problem by removing duplicates from the list of subid mappings in `dynidtools`.
`idtools` (`/etc/subuid` handling) is left untouched.
> Remove duplicate id ranges returned by getsubu/gid for username/uid

- .github/workflows/main.yaml
- Dockerfile
- cmd/rootlesskit-docker-proxy/main.go
- cmd/rootlesskit/category.go
- cmd/rootlesskit/main.go
- docs/network.md
- docs/port.md
- hack/benchmark-iperf3-net.sh
- hack/benchmark-iperf3-port-udp.sh
- hack/benchmark-iperf3-port.sh
- hack/integration-docker.sh
- pkg/network/pasta/pasta.go
Pasta: https://passt.top/passt/
Usage: `rootlesskit --net=pasta --port-driver=implicit`
- No support for explicit port forwarding (`rootlessctl add-ports`),
as pasta doesn't support it yet.
Use `--port-driver=implicit` to let pasta forward TCP ports implicitly.
The forwarded ports are not visible in `rootlessctl list-ports`.
- No support for forwarding UDP ports
- Tested with pasta 2023_06_25.32660ce on Ubuntu 23.04.
Doesn't work with 2023_06_03.429e1a7: `Option --no-copy-routes needs --config-net`
(This is printed despite that `--no-copy-routes` is not specified)
- Doesn't work with Ubuntu 23.04's dpkg (passt_0.0~git20230216.4663ccc-1_amd64.deb):
`Couldn't open user namespace /proc/51813/ns/user: Permission denied`
Likely to be related to AppArmor.
`sudo apparmor_parser -R …
> new network driver: `pasta` (with port driver `implicit`)

- .github/workflows/main.yaml
- pkg/api/client/client.go
- pkg/api/router/router.go
- pkg/network/lxcusernic/lxcusernic.go
fix https://github.com/rootless-containers/rootlesskit/issues/380
> lxc-user-nic: support detach-netns

- pkg/parent/parent.go
- pkg/parent/warn.go
For:
- containerd/nerdctl#2847
- moby/moby#47480
Example output:
```console
$ ~/bin/rootlesskit bash
WARN[0000] [rootlesskit:parent] This error might have happened because /proc/sys/kernel/apparmor_restrict_unprivileged_userns is set to 1  error="fork/exec /proc/self/exe: permission denied"
WARN[0000] [rootlesskit:parent] Hint: try running the following commands:
########## BEGIN ##########
cat <<EOT | sudo tee "/etc/apparmor.d/home.suda.bin.rootlesskit"
abi <abi/4.0>,
include <tunables/global>
/home/suda/bin/rootlesskit flags=(unconfined) {
userns,
include if exists <local/home.suda.bin.rootlesskit>
}
EOT
sudo systemctl restart apparmor.service
########## END ##########
[rootlesskit:parent] error: failed to start the child: fork/exec /proc/self/exe: permission denied
```
> Print hints if `kernel.apparmor_restrict_unprivileged_userns` is set

- hack/integration-systemd-socket.sh
- pkg/child/child.go
- pkg/parent/parent.go
Fixes: #428
This is my first time writing go code, so go easy on me :)
I tried to break this down into a clear set of commits, so the actual logic I want to implement is easy to follow separate from the necessary refactoring I did. Happy to squash this down into one commit though if that is the etiquette around here.
> Support systemd socket activation

- cmd/rootlesskit/main.go
- pkg/network/none/none.go
This PR will add net `none` driver support. The driver almost similar with `host` but only provide `lo` interface configured. This is follow up from https://github.com/rootless-containers/rootlesskit/pull/427 .
> feat: add new none network

- pkg/child/resolvconf.go
- pkg/messages/messages.go
- pkg/network/lxcusernic/lxcusernic.go
- pkg/network/pasta/pasta.go
- pkg/network/slirp4netns/slirp4netns.go
- pkg/network/vpnkit/vpnkit.go
libslirp will provide DNS to the "guest side" simply by forwarding IPv4 UDP packets to the IPv4 host nameserver and idem for IPv6.
See https://gitlab.freedesktop.org/slirp/libslirp/-/blob/6ea2c4f95922a64d21190d9ad163e3bbde37a836/src/socket.c#L971
and https://gitlab.freedesktop.org/slirp/libslirp/-/blob/6ea2c4f95922a64d21190d9ad163e3bbde37a836/src/socket.c#L990
On a host with only IPv4 or IPv6 nameservers this will make only `10.0.2.3` or `fd00::3` functional.
This PR will fix DNS issues on hosts with only IPv6 DNS (such as on a network using NAT64 and DNS64 without client-side address translation) by advertising to the child process the Slirp IPv6 DNS address.
> Fix DNS not being accessible with slirp4netns on hosts with IPv6-only nameservers

- .github/workflows/main.yaml
- Dockerfile
- cmd/rootlesskit/main.go
- hack/integration-systemd-socket-check-env.sh
- hack/integration-systemd-socket.sh
- pkg/child/child.go
- pkg/parent/parent.go
- pkg/systemd/activation/activation.go
Proposal on https://github.com/rootless-containers/rootlesskit/issues/448
Fixing LISTEN_PID env variable for target process if it equals to PID of [rootlless:parent] process.
Tested with dockerd. Extra $$ script is not required anymore.
```Shell
systemd-socket-activate -E "XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}" -l 12312 \
./rootlesskit/rootlesskit --net=slirp4netns --slirp4netns-sandbox=true \
--slirp4netns-seccomp=true \
--disable-host-loopback \
--port-driver=slirp4netns \
--copy-up=/etc \
--copy-up=/run \
sh -c 'rm /run/docker ; exec dockerd -H fd://'
```
Can be demonstated.
```Shell 
> (timeout 10 systemd-socket-activate -l 12345 ./rootlesskit --pidns sh -c 'echo "\$\$ is $$; LISTEN_PID is $LISTEN_PID"' &); sleep 1; netcat localhost 12345
Listening on [::]:12345 as 3.
Communication …
```
> Add execution branch for socket activation to correct LISTEN_PID

- pkg/child/child.go
- pkg/network/lxcusernic/lxcusernic.go
- pkg/network/network.go
- pkg/network/pasta/pasta.go
- pkg/network/slirp4netns/slirp4netns.go
- pkg/network/vpnkit/vpnkit.go
Fixes https://github.com/moby/moby/issues/48257
> Let pasta configure interface, fix IPv6 outbound connectivity

- Makefile
- README.md
- cmd/rootlesskit-docker-proxy/main.go
The rootlesskit-docker-proxy binary is no longer needed since Docker v28, as the functionality of rootlesskit-docker-proxy is now provided by dockerd itself.
https://github.com/moby/moby/pull/48132/commits/dac7ffa3404138a4f291c16586e5a2c68dad4151
rootlesskit-docker-proxy will be removed in RootlessKit v3.
> Deprecate rootlesskit-docker-proxy (no longer needed since Docker v28)

- docs/network.md
- pkg/network/pasta/pasta.go
As suggested in https://github.com/rootless-containers/rootlesskit/pull/458#pullrequestreview-2242422678
> Update comment and network guide to reflect current status of pasta's AppArmor issue on Ubuntu

- pkg/port/builtin/parent/parent.go
When trying to forward sctp port we get a useless
"rootlessport spec was not validated" error back even though the spec was validated before. It is not clear to me if other drivers support sctp here so I didn't want to change ValidatePortSpec to disallow sctp.
As such simply return a useful error saying the protocol is not supported.
> port/builtin: return proper error for sctp

- pkg/port/builtin/child/child.go
- pkg/port/builtin/msg/msg.go
When containerd is running as a root user and an address other than `127.0.0.1`, such as `127.0.0.2`, is specified in `-p` when `nerdctl run` is used to start a container, the combination of the address and port number allows connections to an application running in the container.
Specifically, `curl 127.0.0.2:8080` will access a nginx application running on port `80` in the container created by the following command.
```
$ sudo nerdctl run --name nginx -d -p 127.0.0.2:8080:80 nginx
7abce48d42ef809613365ffaa54d9526e8388c78f5f5c2d8a2850628543ca27e
$ sudo nerdctl ps
CONTAINER ID    IMAGE                             COMMAND                   CREATED          STATUS    PORTS                     NAMES
7abce48d42ef    docker.io/library/nginx:latest    "/docker-entrypoint.…"    3 seconds ago …
```
> fix: allow to propagate the address specified in -p option

- cmd/rootlesskit/main.go
- cmd/rootlesskit/unshare/unshare.go
- pkg/child/child.go
On Ubuntu 25.04, `unshare` is subject to `/etc/apparmor.d/unshare-userns-restrict` that disables mounting.
```
$ rootlesskit --detach-netns bash
[rootlesskit:child ] error: failed to create a detached netns on "/tmp/rootlesskit2294453251/netns":
failed to execute [unshare -n mount --bind /proc/self/ns/net /tmp/rootlesskit2294453251/netns]:
exit status 32 (out="mount: /tmp/rootlesskit2294453251/netns: permission denied.\n       dmesg(1) may have more information after failed mount system call.\n")
```
Fix #494
Alternative to PR #495
> Fix detach-netns permission error on Ubuntu 25.04

- cmd/rootlesskit/main.go
- cmd/rootlesskit/unshare/unshare.go
- pkg/child/child.go
- pkg/version/version.go
This reverts commit 0dfe464daa35d7bfcfe28684b2a31acfd88a0a9f.
- - -
Revert:
- #497 
Due to a regression https://github.com/moby/buildkit/pull/5825#issuecomment-2709212950
> This might be a regression in v2.3.3
> 
> - [test / run (oci-rootless-slirp4netns-detachnetns, ./frontend/dockerfile, dockerfile)](https://github.com/moby/buildkit/actions/runs/13754657207/job/38460231004?pr=5825)
> 
> ```
> === FAIL: frontend/dockerfile TestIntegration (0.05s)
>     run.go:315: copied local:/mainline.tar to local mirror localhost:44447/buildkit_test/mtd7m2emwrrj5deqz9jduk2hb:latest
> time="2025-03-10T01:18:46Z" level=info msg="fetch failed after status: 404 Not Found" host="localhost:44447"
>     run.go:315: copied docker.io/amd64/alpine:latest@sha256:25fad2a32ad1f6f510e528448ae1ec69a28ef81916a004d3629 …
```
> Revert "detach-netns: simplify unshare helper"

- Dockerfile
This PR adds parameter into Dockerfile for ISA of binaries used during image build.
The default value is x86_64 as before.
This PR tested with aarch64, and it could be specified by `--build-arg ARCH=aarch64` options of `docker build` command.
> Arch in dockerfile
